---
- name: check hostname of server
  hosts: Win
  become: true  
  
  tasks:

    - name: check hostname
      win_shell: hostname
      register: fqdn
    
    - name: Display the fqdn
      debug:
        var: fqdn
    
    - name: Install DHCP with sub features and management tools
      win_feature:
        name: DHCP
        state: present
        include_sub_features: yes
        include_management_tools: yes
        reboot_required: False
      register: win_feature
    
    - name: Display the win_feature
      debug:
        var: win_feature

    
